"""initial 9 tables

Revision ID: 5a243df1fb4d
Revises: 
Create Date: 2026-09-30 04:13:47.381093
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '5a243df1fb4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gen_instances',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('placement', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('ws_url', sa.Text(), nullable=True),
    sa.Column('api_key_enc', sa.String(length=512), nullable=True),
    sa.Column('auth_style', sa.String(length=24), server_default='none', nullable=False),
    sa.Column('site', sa.String(length=16), nullable=True),
    sa.Column('instance_type', sa.String(length=16), nullable=True),
    sa.Column('retain_seconds', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('local_output_root', sa.Text(), nullable=True),
    sa.Column('tunnel_name', sa.String(length=128), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('quota', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('cost_total', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('circuit_open', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_probe_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_probe_ok', sa.Boolean(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("placement in ('local','cloud_self','cloud_runninghub')", name='ck_gen_placement'),
    sa.CheckConstraint("protocol in ('comfy_native','rh_task')", name='ck_gen_protocol'),
    sa.CheckConstraint('retain_seconds is null or (retain_seconds between 10 and 180)', name='ck_gen_retain'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_gen_placement_default', 'gen_instances', ['placement', 'is_default'], unique=False)
    op.create_table('llm_backends',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('api_key_enc', sa.String(length=512), nullable=True),
    sa.Column('chat_path', sa.String(length=64), server_default='/chat/completions', nullable=False),
    sa.Column('stream_style', sa.String(length=12), server_default='sse', nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_probe_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_probe_ok', sa.Boolean(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('ollama','openai_compat')", name='ck_llm_kind'),
    sa.CheckConstraint("scope in ('local','cloud')", name='ck_llm_scope'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_llm_scope_default', 'llm_backends', ['scope', 'is_default'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'editor', 'viewer', name='user_role'), server_default='editor', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('max_concurrent_jobs', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('daily_money_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_concurrent_jobs >= 0', name='ck_users_concurrent_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name='uq_audit_id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('project_key', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.String(length=128), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('thumb_path', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime', sa.String(length=128), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('origin', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_media_deleted_at'), 'media', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_media_owner_id'), 'media', ['owner_id'], unique=False)
    op.create_index(op.f('ix_media_project_key'), 'media', ['project_key'], unique=False)
    op.create_index('ix_media_project_role', 'media', ['project_key', 'role', 'ref_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.BigInteger(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by'], ['refresh_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('family', sa.String(length=24), server_default='video', nullable=False),
    sa.Column('source_format', sa.String(length=8), nullable=False),
    sa.Column('graph', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ui_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('slots', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('object_info_hash', sa.String(length=64), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('ix_workflows_family_name', 'workflows', ['family', 'name'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('project_key', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', postgresql.ENUM('llm_chat', 'image', 'video', 'video_chain', 'upscale', 'detect_shots', 'assemble', 'workflow_test', name='job_kind'), nullable=False),
    sa.Column('state', postgresql.ENUM('queued', 'dispatching', 'running', 'succeeded', 'failed', 'canceled', name='job_state'), server_default='queued', nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=True),
    sa.Column('llm_backend_id', sa.BigInteger(), nullable=True),
    sa.Column('workflow_id', sa.BigInteger(), nullable=True),
    sa.Column('prompt_id', sa.String(length=36), nullable=True),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('queue_pos', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output', postgresql.ARRAY(sa.BigInteger()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('cost', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('log', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0', name='ck_jobs_attempts_nonneg'),
    sa.ForeignKeyConstraint(['instance_id'], ['gen_instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['llm_backend_id'], ['llm_backends.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_jobs_owner_id'), 'jobs', ['owner_id'], unique=False)
    op.create_index('ix_jobs_owner_recent', 'jobs', ['owner_id', 'created_at'], unique=False)
    op.create_index('ix_jobs_pick', 'jobs', ['instance_id', 'priority', 'id'], unique=False, postgresql_where=sa.text("state IN ('queued','dispatching')"))
    op.create_index(op.f('ix_jobs_project_key'), 'jobs', ['project_key'], unique=False)
    op.create_index('ix_jobs_project_kind', 'jobs', ['project_key', 'kind', 'created_at'], unique=False)
    op.create_table('instance_locks',
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['gen_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('instance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instance_locks')
    op.drop_index('ix_jobs_project_kind', table_name='jobs')
    op.drop_index(op.f('ix_jobs_project_key'), table_name='jobs')
    op.drop_index('ix_jobs_pick', table_name='jobs', postgresql_where=sa.text("state IN ('queued','dispatching')"))
    op.drop_index('ix_jobs_owner_recent', table_name='jobs')
    op.drop_index(op.f('ix_jobs_owner_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_workflows_family_name', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_media_project_role', table_name='media')
    op.drop_index(op.f('ix_media_project_key'), table_name='media')
    op.drop_index(op.f('ix_media_owner_id'), table_name='media')
    op.drop_index(op.f('ix_media_deleted_at'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_index('ix_llm_scope_default', table_name='llm_backends')
    op.drop_table('llm_backends')
    op.drop_index('ix_gen_placement_default', table_name='gen_instances')
    op.drop_table('gen_instances')
    # ### end Alembic commands ###
